package com.fr4231gm.cismanmonitor.domain;

public enum TipoAccion {
    ACTIVAR_RIEGO,
    DESACTIVAR_RIEGO,
    VER_SENSOR,
    MODIFICAR_CONTRASEÑA_MAESTRA,
    MODIFICAR_PERFIL_RIEGO,
    ACTIVAR_SISTEMA_ANTIPLAGAS,
    DESACTIVAR_SISTEMA_ANTIPLAGAS
}